export const OZON_CITIES = [
  { id: 1, name: 'Casablanca' },
  { id: 2, name: 'Rabat' },
  { id: 3, name: 'Salé' },
  { id: 4, name: 'Témara' },
  { id: 5, name: 'Mohammedia' },
  { id: 6, name: 'Marrakech' },
  { id: 7, name: 'Fès' },
  { id: 8, name: 'Tanger' },
  { id: 9, name: 'Agadir' },
  { id: 10, name: 'Meknès' },
  { id: 11, name: 'Oujda' },
  { id: 12, name: 'Kénitra' },
  { id: 13, name: 'Tétouan' },
  { id: 14, name: 'Nador' },
  { id: 15, name: 'Béni Mellal' },
  { id: 16, name: 'El Jadida' },
  { id: 17, name: 'Taza' },
  { id: 18, name: 'Safi' },
  { id: 19, name: 'Khouribga' },
  { id: 20, name: 'Settat' },
  { id: 21, name: 'Berrechid' },
  { id: 22, name: 'Khénifra' },
  { id: 23, name: 'Larache' },
  { id: 24, name: 'Ksar El Kebir' },
  { id: 25, name: 'Guelmim' },
  { id: 26, name: 'Dakhla' },
  { id: 27, name: 'Laâyoune' },
  { id: 28, name: 'Berkane' },
  { id: 29, name: 'Taourirt' },
  { id: 30, name: 'Bouskoura' },
  { id: 31, name: 'Dar Bouazza' },
  { id: 32, name: 'Tit Mellil' },
  { id: 33, name: 'Nouaceur' },
  { id: 34, name: 'Had Soualem' },
  { id: 35, name: 'Aïn El Aouda' },
  { id: 36, name: 'Skhirat' },
  { id: 37, name: 'Bouznika' },
  { id: 38, name: 'Sidi Slimane' },
  { id: 39, name: 'Sidi Kacem' },
  { id: 40, name: 'Souk El Arbaâ' },
  { id: 41, name: 'Chefchaouen' },
  { id: 42, name: 'Al Hoceïma' },
  { id: 43, name: 'Taroudant' },
  { id: 44, name: 'Tiznit' },
  { id: 45, name: 'Ouarzazate' },
  { id: 46, name: 'Errachidia' },
  { id: 47, name: 'Midelt' },
  { id: 48, name: 'Ifrane' },
  { id: 49, name: 'Azrou' },
  { id: 50, name: 'Khémisset' },
  { id: 51, name: 'Youssoufia' },
  { id: 52, name: 'Essaouira' },
  { id: 53, name: 'Tan-Tan' },
  { id: 54, name: 'Sidi Bennour' },
  { id: 55, name: 'Azemmour' },
  { id: 56, name: 'Martil' },
  { id: 57, name: 'Fnideq' },
  { id: 58, name: 'M\'diq' },
  { id: 59, name: 'Asilah' },
  { id: 60, name: 'Guercif' }
]
